### ISSUE TITLE
Compile Error when building paper with Scriptorium

### ISSUE THREAD

**Issue by rjgriffin42** [jasedit/vtthesis#5]
When executing the "scriptorium build" command after making a new paper of type vtthesis, the following error is reported:

'''
Package hyperref Message: Driver (autodetected): hpdftex.

(/usr/share/texlive/texmf-dist/tex/latex/hyperref/hpdftex.def
(/usr/share/texlive/texmf-dist/tex/latex/oberdiek/rerunfilecheck.sty))
(/usr/share/texlive/texmf-dist/tex/latex/booktabs/booktabs.sty)
(/usr/share/texlive/texmf-dist/tex/latex/tabulary/tabulary.sty
(/usr/share/texlive/texmf-dist/tex/latex/tools/array.sty))

! LaTeX Error: File `biblatex.sty' not found.

Type X to quit or <RETURN> to proceed,
or enter new name. (Default extension: sty)

Enter file name: 
! Emergency stop.
<read *> 
         
l.40 \renewcommand
                  {\bibliography}[1]{\addbibresource{#1.bib}}^^M
!  ==> Fatal error occurred, no output PDF file produced!
Transcript written on paper.log.
'''

**Comment by jasedit** [comment]
What OS is this on? That often is an error in biblatex not being installed as part of the LaTeX package.

**Comment by rjgriffin42** [comment]
Installing both biblatex and biber, using 

`sudo apt-get install texlive-bibtex-extra; sudo apt-get install texlive-bibtex-extra biber`

fixed the issue.

It then threw an error saying it couldn't find the `myabstract` definition, so I had to create a dummy `abstract.tex` file. Not sure if that's an actual error, bug, or what, just thought you should know it as a data point.

**Comment by jasedit** [comment]
`myabstract` is part of the required frontmatter (and is listed in the Readme), and doesn't have any protections against not existing, since VT requires the abstract for any thesis. Glad to hear the problem was easily resolved however!

**Comment by rjgriffin42** [comment]
In that case, is there any way to have scriptorium, when creating a new paper of type vtthesis, such as through 

`scriptorium new example_report -t vtthesis -c author "John Doe" -c title "My Example Report"`

auto-create a file named `abstract.tex`? Just a thought.

Also, thanks for the quick response time!
